"""
Demo Script for Future Trading Bot
This script demonstrates the bot's capabilities with sample data
"""

import asyncio
import os
from datetime import datetime
from bot import FutureTradingBot, TradingSignal

async def demo_bot():
    """Demo function to show bot capabilities"""
    print("Future Trading Bot - Demo Mode")
    print("=" * 50)
    print("This demo shows how the bot generates trading signals")
    print("For live trading, set your OPENAI_API_KEY environment variable")
    print("=" * 50)
    
    # Check if OpenAI API key is available
    api_key = os.getenv('OPENAI_API_KEY', 'demo-key-not-set')
    
    if api_key == 'demo-key-not-set':
        print("⚠️  OpenAI API key not set - running in demo mode")
        print("   Set OPENAI_API_KEY environment variable for full functionality")
        print()
    
    # Initialize bot
    target_symbols = ['USD/BRL', 'USD/CAD', 'NZD/CAD']
    bot = FutureTradingBot(api_key, target_symbols)
    
    print("Generating sample trading signals...")
    print()
    
    # Generate sample signals
    sample_signals = []
    
    for symbol in target_symbols:
        # Create sample signal (normally generated by AI analysis)
        signal = TradingSignal(
            symbol=symbol,
            signal_type="BUY" if symbol == "USD/BRL" else "SELL" if symbol == "USD/CAD" else "HOLD",
            confidence=0.75 if symbol == "USD/BRL" else 0.65 if symbol == "USD/CAD" else 0.55,
            entry_price=0.169 if symbol == "USD/BRL" else 0.755 if symbol == "USD/CAD" else 0.892,
            stop_loss=0.166 if symbol == "USD/BRL" else 0.770 if symbol == "USD/CAD" else 0.888,
            take_profit=0.176 if symbol == "USD/BRL" else 0.725 if symbol == "USD/CAD" else 0.896,
            timestamp=datetime.now(),
            reasoning=f"Demo signal for {symbol} - technical analysis indicates {'bullish' if symbol == 'USD/BRL' else 'bearish' if symbol == 'USD/CAD' else 'neutral'} momentum",
            timeframe="5m"
        )
        sample_signals.append(signal)
    
    # Display signals
    bot.display_signals(sample_signals)
    
    print("\nDemo completed!")
    print("To run the live bot:")
    print("1. Set your OpenAI API key: set OPENAI_API_KEY=your_key_here")
    print("2. Run: python bot.py")

if __name__ == "__main__":
    asyncio.run(demo_bot())
